In [2]:
# https://pytorch.org/tutorials/beginner/introyt/introyt1_tutorial.html 
# https://pytorch.org/get-started/locally/

import torch
# x = torch.rand(5, 3)
# print(x)

In [4]:
z = torch.zeros(5, 3)
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
z.dtype

torch.float32

In [10]:
i = torch.ones((5, 3), dtype=torch.int16)
i

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [11]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
r1

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

In [12]:
r2 = torch.rand(2, 2)
r2

tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

In [13]:
torch.manual_seed(1729) 
r3 = torch.rand(2, 2) # same as r1 as same seed
r3

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

In [14]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
twos = torch.ones(2, 3) * 2
twos

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [16]:
threes = ones + twos
threes

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [17]:
threes.shape

torch.Size([2, 3])

In [49]:
r = torch.rand(2, 2) - 0.5 * 2 # numbers between -1 and 1
r

tensor([[-0.2699, -0.3724],
        [-0.2643, -0.9619]])

In [50]:
torch.abs(r)

tensor([[0.2699, 0.3724],
        [0.2643, 0.9619]])

In [51]:
torch.asin(r)

tensor([[-0.2733, -0.3816],
        [-0.2674, -1.2939]])

In [52]:
torch.det(r)

tensor(0.1612)

In [53]:
torch.svd(r)

torch.return_types.svd(
U=tensor([[ 0.4038,  0.9148],
        [ 0.9148, -0.4038]]),
S=tensor([1.0884, 0.1481]),
V=tensor([[-0.3222, -0.9467],
        [-0.9467,  0.3222]]))

In [54]:
torch.std_mean(r)

(tensor(0.3336), tensor(-0.4671))

In [55]:
torch.max(r)

tensor(-0.2643)

In [ ]:
# Autograd
x = torch.randn(1, 10)
prev_h = torch.rand(1, 20)
W_h = torch.rand(20, 20)
W_x = torch.rand(20, 10)

i2h = torch.mm(W_x, x.t())
h2h = torch.mm(W_h, prev_h.t())
next_h = i2h + h2h
next_h = next_h.tanh()

loss = next_h.sum()
loss.backward()